### ISSUE TITLE
Difficulty when running in parallel

### ISSUE THREAD

**Issue by ramongonze** [IBM/differential-privacy-library#40]
Hello,

I'm trying to use mechanisms from diffprivlib and calling **randomise** methods in parallel, but I'm getting an error related to random library. Below there is a simple example using ```joblib``` library (the same used in diffprivlib.LogisticRegression) to execute it in parallel:

```python
from joblib import Parallel, delayed
from diffprivlib.mechanisms import GeometricTruncated

mec = GeometricTruncated(epsilon=2, sensitivity=1, lower=1, upper=10)
path_func = delayed(mec.randomise)
res = list(Parallel(n_jobs=2, prefer='processes')(
    path_func(value) for value in range(10))
)

print(res)
```

I get the following error:

```
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ramon/anaconda3/lib/python3.8/site-packages/joblib/externals/loky/backend/queues.py", line 153, in _feed
    obj_ = dumps(obj, reducers=reducers)
  File "/home/ramon/anaconda3/lib/python3.8/site-packages/joblib/externals/loky/backend/reduction.py", line 271, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "/home/ramon/anaconda3/lib/python3.8/site-packages/joblib/externals/loky/backend/reduction.py", line 264, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/home/ramon/anaconda3/lib/python3.8/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
  File "/home/ramon/anaconda3/lib/python3.8/random.py", line 196, in __reduce__
    return self.__class__, (), self.getstate()
  File "/home/ramon/anaconda3/lib/python3.8/random.py", line 735, in _notimplemented
    raise NotImplementedError('System entropy source does not have state.')
NotImplementedError: System entropy source does not have state.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "a.py", line 6, in <module>
    res = list(Parallel(n_jobs=2, prefer='processes')(
  File "/home/ramon/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/home/ramon/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ramon/anaconda3/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ramon/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/ramon/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
_pickle.PicklingError: Could not pickle the task to send it to the workers.
```

I've already tried to use python ```multiprocessing.Pool``` but I also get the error ```System entropy source does not have state.```
I've already tried to change the Parallel backend to ```"multiprocessing"``` instead of ```loky```, but also get the same error.

I couldn't find solutions or related issues. Could you please help?

System settings used in the example:
- **OS:** Ubuntu 21.10
- **python:** 3.8.5
- **diffprivlib:** 0.4.1

**Comment by naoise-h** [comment]
Hi there,

The issue here is that random number generators from the `secrets` library (the default for most mechanisms) does not have a state, as it's a cryptographic RNG. You can fix this by switching to a numpy RNG manually, by adding this line after initialising `mec`:
```python
import numpy as np
mec._rng = np.random.default_rng()
```

This results in some issues with how joblib pickles `mec`, which results in highly-correlated outputs. But there is some strange behaviour which I can't quite explain. However, it seems that changing the `Parallel` call to prefer "threads" fixes this.

Your MWE should therefore work using the following:
```python
import numpy as np
from joblib import Parallel, delayed
from diffprivlib.mechanisms import GeometricTruncated

mec = GeometricTruncated(epsilon=2, sensitivity=1, lower=1, upper=10)
mec._rng = np.random.default_rng()
path_func = delayed(mec.randomise)
res = list(Parallel(n_jobs=2, prefer='threads')(
    path_func(value) for value in range(10))
)

print(res)
```
