### ISSUE TITLE
diffprivlib failed to be installed in Windows 10 due to the crlibm dependency

### ISSUE THREAD

**Issue by shlomihod** [IBM/differential-privacy-library#66]
**Describe the bug**
Cannot install `diffprivlib` in Windows because of the dependency in [`crlibm`](https://github.com/taschini/pycrlibm), whichi requires compilation in Windows.

**To Reproduce**
On Windows, `pip install diffprivlib`.
Make sure that gcc/g++ is installed and accessible in PATH (e.g., using [MSYS2](https://www.msys2.org/).

**Expected behavior**
The packaged `diffprivlib` is installed.

**Screenshots**
```cmd
PS C:\projects\test> pip install crlibm --no-cache
Collecting crlibm
  Downloading crlibm-1.0.3.tar.gz (1.6 MB)
     |████████████████████████████████| 1.6 MB 6.4 MB/s
Building wheels for collected packages: crlibm
  Building wheel for crlibm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Shlomi\miniconda3\envs\synthflow\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Shlomi\\AppData\\Local\\Temp\\pip-install-rc0mt5z4\\crlibm_02a44f0616a14f67b308a667aff2cb0d\\setup.py'"'"'; __file__='"'"'C:\\Users\\Shlomi\\AppData\\Local\\Temp\\pip-install-rc0mt5z4\\crlibm_02a44f0616a14f67b308a667aff2cb0d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Shlomi\AppData\Local\Temp\pip-wheel-c3zxz8jw'
       cwd: C:\Users\Shlomi\AppData\Local\Temp\pip-install-rc0mt5z4\crlibm_02a44f0616a14f67b308a667aff2cb0d\
  Complete output (42 lines):
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Shlomi\AppData\Local\Temp\pip-install-rc0mt5z4\crlibm_02a44f0616a14f67b308a667aff2cb0d\setup.py", line 189, in <module>
      setup(**metadata)
    File "C:\Users\Shlomi\miniconda3\envs\synthflow\lib\site-packages\setuptools\__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\Shlomi\miniconda3\envs\synthflow\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
      return run_commands(dist)
    File "C:\Users\Shlomi\miniconda3\envs\synthflow\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
      dist.run_commands()
    File "C:\Users\Shlomi\miniconda3\envs\synthflow\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "C:\Users\Shlomi\miniconda3\envs\synthflow\lib\site-packages\setuptools\dist.py", line 1214, in run_command
      super().run_command(command)
    File "C:\Users\Shlomi\miniconda3\envs\synthflow\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\Shlomi\miniconda3\envs\synthflow\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\Shlomi\miniconda3\envs\synthflow\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Shlomi\miniconda3\envs\synthflow\lib\site-packages\setuptools\dist.py", line 1214, in run_command
      super().run_command(command)
    File "C:\Users\Shlomi\miniconda3\envs\synthflow\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\Shlomi\miniconda3\envs\synthflow\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\Shlomi\miniconda3\envs\synthflow\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Shlomi\miniconda3\envs\synthflow\lib\site-packages\setuptools\dist.py", line 1214, in run_command
      super().run_command(command)
    File "C:\Users\Shlomi\miniconda3\envs\synthflow\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\Shlomi\miniconda3\envs\synthflow\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 305, in run
      self.compiler = new_compiler(compiler=self.compiler,
    File "C:\Users\Shlomi\miniconda3\envs\synthflow\lib\site-packages\setuptools\_distutils\ccompiler.py", line 1039, in new_compiler
      return klass(None, dry_run, force)
    File "C:\Users\Shlomi\AppData\Local\Temp\pip-install-rc0mt5z4\crlibm_02a44f0616a14f67b308a667aff2cb0d\setup.py", line 59, in __init__
      shared_option = "-shared" if self.ld_version >= "2.13" else "-mdll -static"
  AttributeError: 'Msys2CCompiler' object has no attribute 'ld_version'
  ----------------------------------------
  ERROR: Failed building wheel for crlibm
```

**Root cause of the bug**
I believe that the `setup.py` file of `crlibm` uses an old API of `setuptools`. In particular, it looks for the attribute `ld_version` ([reference](https://github.com/taschini/pycrlibm/blob/4e44df33af855a31cee89cced4e894a06a947712/setup.py#L59)) that does not exists anymore for `distutils.cygwinccompiler.CygwinCCompiler` (I couldn't track the exact commit where this change was made, but this is the version I'm having [ref](https://github.com/pypa/setuptools/blob/v62.2.0/setuptools/_distutils/cygwinccompiler.py)).

**System information (please complete the following information):**
 - OS: Windows 10 Pro
 - Python version: 3.8 (using miniconda environment but installation with pip)
 - Shell: Powershell
 - diffprivlib version or commit number

**Comment by naoise-h** [comment]
Hi, have you tried installing an older version of `setuptools` to be able to install `crlibm`? This can be done by running the pip command `pip install setuptools==62.0.0`, for example. Once `crlibm` is installed, you can then update `setuptools` again.

**Comment by shlomihod** [comment]
Thanks for the idea! I explored this direction; however, I'm using poetry to manage my dependencies and it includes its own version of setuptools. I decided to vendor the functionality I needed from diffprivlib into my package. 

crlibm is used exactly once in diffprivlib for the Snapping mechanism (which I don't need un my use case) - perhaps it should installed only as pip extension?

**Comment by naoise-h** [comment]
With #67 now merged, this bug is solved in main, and will be included in the next release of diffprivlib. Thanks for flagging this for us.
